services:
  db:
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: strongpassword
      MARIADB_DATABASE: laravel
      MARIADB_USER: laravel
      MARIADB_PASSWORD: laravel
    volumes:
      - db_data:/var/lib/mysql  
    ports:
      - "3306:3306"

  adminer:
    image: adminer
    ports:
      - "8080:8080"

  
  laravel:
    build: ./
    ports:
      - "8000:80"
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_DATABASE: laravel
      DB_USERNAME: laravel
      DB_PASSWORD: laravel
      DB_PORT: 3306

volumes:
  db_data: